sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NY90DTgGrYwDpJamJKMrRyssn4iBwbmKGCa8FOKMeklNKbuY+A6uYJaO3AopsKHgF+8jv5S/AoHroXXM1mnhtX7vQbwQQxWv1/U36Z8B2SPlxpWo0XRROqp2aAJ6AiD1E/y2qqOzFvrB2xae1oxWXx/YprOAPp7KCc4E0plmytsxUUWkMv8/Ov7Add9Ahf80ghINqutsG+BzjR1bb73mggDsiaTXs1Vp1dqq5Hdi0sLIEqqmfbcfUvbgbvlx2hBjZ5xtUdk1sRrXIqVv/+uGawp0o/eXKVwBew4gKGMXLelMADkbl5az9WH8RiWlxvD5o9wJEUehPXDUxjNXen0t0e29wRXw36HReEJK6RkoH0dNU9sXF54M9HXJBmxzDS6Ohsw3bckzjm3AgZYUFIjXdAoIPpRptqkJQKve8ttxJ0OmmsjYB4UJK2HselqVjZa6FkGybmEAqSjR4ZHfcZZSTrt2cpXTLHi4b8VTEkh3FWHooFKgosr0GI25DFnshLjxIfubWHzNZ5elPlN8wOg/zzJil8hfp9CimtS4Afdfk6Uuf+/RXM12kyWwhfMBENEbRRV83kLY9wvDtYKEl5T+NSi1t/FCD1HCe9kFY3djduwbzT/GBM8zKyztfSZcZQBAjZ6IpYYz1WIxSmyiv3PZLkbhLGYwrJrDbWXY7/I+n1M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Novel-and-the-Common-School_3123
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy